---
- name: Ensure system dependencies are installed
  hosts: claroty_servers
  become: true
  tasks:
    - name: Install required packages
      ansible.builtin.package:
        name:
          - python3
          - docker.io
          - curl
          - net-tools
        state: present
